__version__: 1.3.1
transform:
  __class_fullname__: Compose
  additional_targets: {}
  bbox_params: null
  is_check_shapes: true
  keypoint_params: null
  p: 1.0
  transforms:
  - __class_fullname__: PadIfNeeded
    always_apply: false
    border_mode: 4
    mask_value: null
    min_height: 512
    min_width: 512
    p: 1.0
    pad_height_divisor: null
    pad_width_divisor: null
    value: 1.0
  - __class_fullname__: Blur
    always_apply: false
    blur_limit:
    - 3
    - 7
    p: 0.125
  - __class_fullname__: GaussNoise
    always_apply: false
    mean: 0
    p: 0.125
    per_channel: true
    var_limit:
    - 10.0
    - 50.0
  - __class_fullname__: PixelDropout
    always_apply: false
    drop_value: 1.0
    dropout_prob: 0.01
    mask_drop_value: null
    p: 0.33
    per_channel: false
  - __class_fullname__: CoarseDropout
    always_apply: false
    fill_value: 1.0
    mask_fill_value: null
    max_height: 13
    max_holes: 10
    max_width: 13
    min_height: 13
    min_holes: 10
    min_width: 13
    p: 0.33
  - __class_fullname__: OneOf
    p: 0.33
    transforms:
    - __class_fullname__: SmallestMaxSize
      always_apply: false
      interpolation: 1
      max_size: 350
      p: 0.5
    - __class_fullname__: RandomCrop
      always_apply: false
      height: 512
      p: 0.5
      width: 512
  - __class_fullname__: CLAHE
    always_apply: false
    clip_limit:
    - 1
    - 4.0
    p: 0.33
    tile_grid_size:
    - 8
    - 8
